import type {
  SiteChatConfig,
  SiteChatConfigInput,
  SiteChatCopy,
  SiteChatMode,
  SiteChatRateLimit,
  SiteChatTransport,
} from "./types.js";

/** Bumped whenever the standard changes in a way projects must react to. */
export const STANDARD_VERSION = "1.0.1";

export const DEFAULT_SESSION_ENDPOINT = "/api/site-chat/session";

export const DEFAULT_COPY: SiteChatCopy = {
  launcher: "Chat with us",
  tagline: "AI assistant",
  inputPlaceholder: "Ask a question…",
  startVoice: "Start voice chat",
  endVoice: "End voice chat",
  empty: "Ask anything. Replies are generated by AI.",
  disclosure: "AI assistant. Responses may be inaccurate — verify anything important.",
  error: "The assistant is unavailable right now. Please try again in a moment.",
};

export const DEFAULT_RATE_LIMIT: SiteChatRateLimit = { windowMs: 60_000, max: 10 };

/**
 * Applies the standard defaults to a project's config.
 *
 * Call this in `site-chat.config.ts` and export the result as the default
 * export. Both the client component and the session route read that file, so it
 * must never contain secrets — the ElevenLabs API key is read from the
 * environment inside the route and never leaves the server.
 */
export function defineSiteChat(input: SiteChatConfigInput): SiteChatConfig {
  if (!input.site) {
    throw new Error("[site-chat] `site` is required.");
  }
  if (!input.agentId) {
    throw new Error(
      "[site-chat] `agentId` is required. Set NEXT_PUBLIC_SITE_CHAT_AGENT_ID in the environment.",
    );
  }
  if (/^sk_|^sk-ant|^xi-/.test(input.agentId)) {
    throw new Error(
      "[site-chat] `agentId` looks like an API key. Agent ids start with `agent_`; " +
        "API keys belong in ELEVENLABS_API_KEY, server-side only.",
    );
  }

  return {
    site: input.site,
    agentId: input.agentId,
    mode: input.mode ?? "text-first",
    auth: input.auth ?? "signed",
    sessionEndpoint: input.sessionEndpoint ?? DEFAULT_SESSION_ENDPOINT,
    brand: {
      name: input.brand.name,
      accent: input.brand.accent ?? "#111827",
      accentForeground: input.brand.accentForeground ?? "#ffffff",
      avatarUrl: input.brand.avatarUrl ?? "",
    },
    placement: input.placement ?? "bottom-right",
    copy: { ...DEFAULT_COPY, ...input.copy },
    rateLimit: { ...DEFAULT_RATE_LIMIT, ...input.rateLimit },
    allowedOrigins: input.allowedOrigins,
    dynamicVariables: input.dynamicVariables,
    environment: input.environment,
    branchId: input.branchId,
    serverLocation: input.serverLocation ?? "us",
    enabled: input.enabled ?? true,
    standardVersion: STANDARD_VERSION,
  };
}

/** Text sessions run over WebSocket; voice runs over WebRTC. */
export function defaultTransportForMode(mode: SiteChatMode): SiteChatTransport {
  return mode === "voice-first" ? "webrtc" : "websocket";
}

/** Whether the surface may ever ask for the microphone. */
export function supportsVoice(mode: SiteChatMode): boolean {
  return mode !== "text-only";
}
